<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="img\back.jpg" />
    <None Remove="img\Bez názvu.png" />
    <None Remove="img\broken.png" />
    <None Remove="img\grimoire.png" />
    <None Remove="img\inventary.png" />
    <None Remove="img\lowPolda.png" />
    <None Remove="img\mahou.png" />
    <None Remove="img\Pankrac.png" />
    <None Remove="img\Polda.png" />
    <None Remove="img\potion.png" />
    <None Remove="img\poza.pxo" />
    <None Remove="img\room.png" />
    <None Remove="img\scroll.png" />
    <None Remove="img\scrollS.png" />
    <None Remove="img\scrollT.png" />
    <None Remove="img\sefirot.png" />
    <None Remove="img\textil.png" />
    <None Remove="img\untitled.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="img\Bez názvu.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\broken.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\grimoire.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\inventary.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\lowPolda.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\mahou.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\potion.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\room.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\scrollS.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\scrollT.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\sefirot.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\textil.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\untitled.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
